Repository maybe-picasso/picasso, pull requests merged in 2022-07, with the labels that each got.

#77 feat: 출제자와 캔버스 사이즈 차이로 인한 좌표 보정 처리
  frontend/src/core/drawing/drawing-core.ts
  frontend/src/core/drawing/drawing.ts
  frontend/src/pages/Room/containers/CanvasContainer/index.tsx
  frontend/src/types/global.d.ts
Labels: 기능

#79 [게임] inactive tab timer 처리 (Fixes #78)
  frontend/package.json
  frontend/src/pages/Room/hooks/useGameHandler.tsx
  frontend/src/store/models/game.ts
  frontend/yarn.lock
Labels: 개선

#81 [게임] 진행중 입장한 유저 진행 상태 싱크 처리
  backend/src/app.socket.ts
  frontend/src/pages/Room/containers/HeaderContainer/index.tsx
  frontend/src/pages/Room/hooks/index.ts
  frontend/src/pages/Room/hooks/useGameHandler.tsx
  frontend/src/pages/Room/hooks/useGameSync.tsx
  frontend/src/pages/Room/index.tsx
  frontend/src/types/enums.ts
Labels: 기능

#83 feat: 배포를 위한 github actions CI 설정
  .github/workflows/deploy-backend.yml
  .github/workflows/deploy-frontend.yml
  backend/package.json
  backend/src/app.socket.ts
  backend/src/main.ts
  backend/yarn.lock
  frontend/.env
  frontend/config-overrides.js
  frontend/package.json
  frontend/src/core/socket.ts
  frontend/src/helpers/env.ts
  frontend/src/index.tsx
  frontend/src/pages/Room/containers/HeaderContainer/index.tsx
  frontend/src/store/models/game.ts
  frontend/yarn.lock
Labels: 환경구성 ⚙️

#84 feat: 배경 컨셉 리디자인
  frontend/src/constants/index.ts
  frontend/src/pages/About/components/CameraControl/index.jsx
  frontend/src/pages/About/components/Clouds/index.tsx
  frontend/src/pages/About/components/Earth/index.tsx
  frontend/src/pages/About/components/Image3D/index.tsx
  frontend/src/pages/About/components/Loading/index.scss
  frontend/src/pages/About/components/Loading/index.tsx
  frontend/src/pages/About/components/Typo3D/index.jsx
  frontend/src/pages/About/index.scss
  frontend/src/pages/About/index.tsx
  frontend/src/pages/Home/index.scss
  frontend/src/pages/Home/index.tsx
  frontend/src/pages/Room/containers/GateContainer/index.scss
  frontend/src/pages/Room/containers/GateContainer/index.tsx
  frontend/src/pages/Room/containers/HeaderContainer/index.scss
  frontend/src/pages/Room/index.scss
  frontend/src/pages/index.ts
  frontend/src/routes/index.tsx
  frontend/src/routes/paths.ts
  frontend/src/stories/1-Home.stories.tsx
  frontend/src/styles/modules/base.scss
  frontend/src/styles/modules/init.scss
  frontend/src/styles/modules/mixin.scss
Labels: 개선 😀, 기능 😀

#90 feat: 유저 목록 응답 로딩중 스켈레톤 추가
  frontend/src/mocks/store/index.ts
  frontend/src/pages/Room/containers/UserListContainer/index.tsx
  frontend/src/stories/2-Room.stories.tsx
Labels: 개선 😀, UI 😀

#92 feat: 전원 조기 정답시 처리 Fixes #86
  frontend/src/pages/Room/hooks/useGameHandler.tsx
Labels: 개선 😀

#91 fix: 채팅창 최신 메시지 스크롤 버튼 추가
  frontend/src/pages/Room/containers/ChatContainer/index.scss
  frontend/src/pages/Room/containers/ChatContainer/index.tsx
Labels: 개선 😀, UI 😀
