Repository maybe-picasso/picasso, pull requests merged in 2022-05, with the labels that each got.

#40 chore: 사용자 목록 이미지 영역 확대
  frontend/src/constants/index.ts
  frontend/src/pages/Room/components/GameTimer/index.scss
  frontend/src/pages/Room/containers/UserListContainer/index.scss
  frontend/src/pages/Room/containers/UserListContainer/index.tsx
Labels: 개선

#39 chore: 퀴즈 단어 영역 요소 추가 및 프로필 키 이벤트 수정
  frontend/src/pages/Room/components/GameQuestion/index.tsx
  frontend/src/pages/Room/components/GameRound/index.scss
  frontend/src/pages/Room/components/GameRound/index.tsx
  frontend/src/pages/Room/components/GameTimer/index.scss
  frontend/src/pages/Room/components/index.ts
  frontend/src/pages/Room/containers/GameHeaderContainer/index.tsx
  frontend/src/pages/Room/containers/GateContainer/index.scss
  frontend/src/pages/Room/containers/GateContainer/index.tsx
  frontend/src/pages/Room/containers/ToolsContainer/index.tsx
Labels: 개선

#41 feat: 스토리북 구성
  frontend/.env
  frontend/.storybook/decorators/index.ts
  frontend/.storybook/decorators/withRedux.tsx
  frontend/.storybook/decorators/withRouter.tsx
  frontend/.storybook/main.js
  frontend/.storybook/preview.js
  frontend/.storybook/style.scss
  frontend/package.json
  frontend/public/favicon-unicon.png
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/helpers/env.ts
  frontend/src/helpers/url.ts
  frontend/src/mocks/store/chat.ts
  frontend/src/mocks/store/index.ts
  frontend/src/mocks/store/room.ts
  frontend/src/pages/PracticeRoom/components/ColorPicker/index.scss
  frontend/src/pages/PracticeRoom/components/ColorPicker/index.tsx
  frontend/src/pages/PracticeRoom/components/ToolSizeSelector/index.scss
  frontend/src/pages/PracticeRoom/components/ToolSizeSelector/index.tsx
  frontend/src/pages/PracticeRoom/index.scss
  frontend/src/pages/PracticeRoom/index.tsx
  frontend/src/pages/Room/containers/SocketContainer/index.tsx
  frontend/src/pages/Room/containers/UserListContainer/index.scss
  frontend/src/pages/index.ts
  frontend/src/routes/index.tsx
  frontend/src/routes/paths.ts
  frontend/src/store/models/chat.ts
  frontend/src/store/models/common.ts
  frontend/src/store/models/room.ts
  frontend/src/store/models/tools.ts
  frontend/src/stories/1-Home.stories.tsx
  frontend/src/stories/2-Room.stories.tsx
  frontend/yarn.lock
Labels: 환경구성

#42 refactor: 인트로 3d 오브젝트 로딩 속도 개선, 폰트 경량화 json 적용
  frontend/public/fonts/Jua_Regular-picaso.json
  frontend/public/textures/cube4.jpg
  frontend/public/textures/cube6.jpg
  frontend/public/textures/earth-clouds.jpg
  frontend/public/textures/earth-specular.jpg
  frontend/src/pages/Home/components/CameraControl/index.jsx
  frontend/src/pages/Home/components/Typo3D/index.jsx
Labels: 개선

#43 feat: 룸 나가기 추가 및 헤더 컨테이너 정리
  frontend/src/pages/Room/containers/CanvasHeaderContainer/index.scss
  frontend/src/pages/Room/containers/CanvasHeaderContainer/index.tsx
  frontend/src/pages/Room/containers/HeaderContainer/index.scss
  frontend/src/pages/Room/containers/HeaderContainer/index.tsx
  frontend/src/pages/Room/containers/index.tsx
  frontend/src/pages/Room/index.scss
  frontend/src/pages/Room/index.tsx
Labels: 기능

#45 feat: 게임 스토어 초기 모델링 및 게임 상황별 케이스 추가
  frontend/package.json
  frontend/src/constants/index.ts
  frontend/src/core/drawing/drawing.ts
  frontend/src/mocks/store/gamePoint.ts
  frontend/src/mocks/store/index.ts
  frontend/src/pages/Room/components/GameQuestion/index.tsx
  frontend/src/pages/Room/components/GameRound/index.tsx
  frontend/src/pages/Room/components/GameTimer/index.tsx
  frontend/src/pages/Room/components/index.ts
  frontend/src/pages/Room/components/overlay/CompleteContent/index.scss
  frontend/src/pages/Room/components/overlay/CompleteContent/index.tsx
  frontend/src/pages/Room/components/overlay/GameOverContent/index.scss
  frontend/src/pages/Room/components/overlay/GameOverContent/index.tsx
  frontend/src/pages/Room/containers/CanvasContainer/index.scss
  frontend/src/pages/Room/containers/GameContentContainer/index.scss
  frontend/src/pages/Room/containers/GameContentContainer/index.tsx
  frontend/src/pages/Room/containers/GateContainer/index.tsx
  frontend/src/pages/Room/containers/UserListContainer/index.scss
  frontend/src/pages/Room/containers/UserListContainer/index.tsx
  frontend/src/pages/Room/containers/index.tsx
  frontend/src/pages/Room/index.tsx
  frontend/src/store/models/game.ts
  frontend/src/store/models/gamePoint.ts
  frontend/src/store/models/index.ts
  frontend/src/store/models/room.ts
  frontend/src/stories/2-Room.stories.tsx
  frontend/src/types/enums.ts
  frontend/src/types/global.d.ts
  frontend/yarn.lock
Labels: 기능

#44 feat: 프로필 초기값을 랜덤하게 노출되도록 함
  frontend/package.json
  frontend/src/helpers/utils.ts
  frontend/src/pages/Room/containers/GateContainer/index.tsx
  frontend/yarn.lock
Labels: 개선

#46 feat: 레이아웃 리사이징시 발생하는 일부 이슈 수정
  frontend/src/constants/index.ts
  frontend/src/pages/Room/components/PaletteColor/index.scss
  frontend/src/pages/Room/containers/CanvasContainer/index.scss
  frontend/src/pages/Room/containers/ToolsContainer/index.tsx
  frontend/src/pages/Room/containers/UserListContainer/index.scss
  frontend/src/pages/Room/index.scss
  frontend/src/pages/Room/index.tsx
Labels: 개선

#50 feat: 문제 푸는 사람 화면 구성
  frontend/src/mocks/store/index.ts
  frontend/src/pages/Room/components/GameQuestion/index.tsx
  frontend/src/pages/Room/containers/GameContentContainer/index.tsx
  frontend/src/pages/Room/containers/GameStatusContainer/index.tsx
  frontend/src/pages/Room/containers/ToolsContainer/index.tsx
  frontend/src/pages/Room/containers/index.tsx
  frontend/src/pages/Room/hooks/index.ts
  frontend/src/pages/Room/hooks/useMyTurn.tsx
  frontend/src/pages/Room/hooks/usePainterInfo.tsx
  frontend/src/pages/Room/index.tsx
  frontend/src/stories/2-Room.stories.tsx
Labels: 기능
