Repository maybe-picasso/picasso, pull requests merged in 2022-06, with the labels that each got.

#51 chore: 스토리북 버전 6.5.6 업데이트
  frontend/package.json
  frontend/yarn.lock
Labels: 환경구성

#64 feat: 시간 종료시 다음 턴으로 바뀌는 처리
  frontend/src/mocks/store/index.ts
  frontend/src/pages/Room/components/GameTimer/index.tsx
  frontend/src/pages/Room/containers/GameContentContainer/index.tsx
  frontend/src/pages/Room/containers/GameStatusContainer/index.tsx
  frontend/src/pages/Room/containers/UserListContainer/index.scss
  frontend/src/pages/Room/hooks/index.ts
  frontend/src/pages/Room/hooks/useGameHandler.tsx
  frontend/src/pages/Room/index.tsx
  frontend/src/store/models/game.ts
  frontend/src/stories/2-Room.stories.tsx
  frontend/src/types/enums.ts
Labels: 기능

#66 feat: undo / redo 기능 추가
  frontend/src/core/drawing/drawing.ts
  frontend/src/types/enums.ts
Labels: 기능

#67 feat: 게임종료 순위발표 레이어
  frontend/package.json
  frontend/src/pages/Room/components/overlay/CompleteContent/index.scss
  frontend/src/pages/Room/components/overlay/CompleteContent/index.tsx
  frontend/src/pages/Room/components/overlay/GameOverContent/index.tsx
  frontend/src/pages/Room/components/overlay/ResultLayer/index.scss
  frontend/src/pages/Room/components/overlay/ResultLayer/index.tsx
  frontend/yarn.lock
Labels: UI

#71 feat: 로컬스토리지 헬퍼 추가
  frontend/src/constants/index.ts
  frontend/src/helpers/storage.ts
  frontend/src/pages/Room/containers/GateContainer/index.tsx
Labels: 기능

#72 feat: 도구 상태 restore 기능 추가
  frontend/src/pages/Room/components/PaletteSlider/index.tsx
  frontend/src/pages/Room/containers/ToolsContainer/index.tsx
  frontend/src/store/models/tools.ts
Labels: 기능

#73 feat: 개발 상태값 로그 추가
  frontend/src/pages/Room/containers/DevLogContainer/index.scss
  frontend/src/pages/Room/containers/DevLogContainer/index.tsx
  frontend/src/pages/Room/containers/index.tsx
  frontend/src/pages/Room/index.tsx
  frontend/src/store/models/game.ts
Labels: 환경구성

#75 feat: tool 아이콘 처리
  frontend/src/assets/img/brush.svg
  frontend/src/assets/img/eraser.svg
  frontend/src/assets/img/trash-can.svg
  frontend/src/pages/Room/containers/CanvasContainer/index.scss
  frontend/src/pages/Room/containers/ToolsContainer/index.scss
  frontend/src/pages/Room/containers/ToolsContainer/index.tsx
  package.json
Labels: UI
