Repository maybe-picasso/picasso, pull requests merged in 2022-08, with the labels that each got.

#96 fix: 채팅 스크롤 바텀 이동 조건 수정
  frontend/src/pages/Room/containers/ChatContainer/index.tsx
Labels: 개선 😀

#97 feat: 정답자 에니메이션 추가
  frontend/package.json
  frontend/src/mocks/store/gamePoint.ts
  frontend/src/mocks/store/index.ts
  frontend/src/pages/Room/components/GameQuestion/index.tsx
  frontend/src/pages/Room/containers/GameContentContainer/index.tsx
  frontend/src/pages/Room/hooks/index.ts
  frontend/src/pages/Room/hooks/useMyCorrect.tsx
  frontend/yarn.lock
Labels: 개선 😀, UI 😀

#98 deploy: Merge to master
  frontend/package.json
  frontend/src/mocks/store/gamePoint.ts
  frontend/src/mocks/store/index.ts
  frontend/src/pages/Room/components/GameQuestion/index.tsx
  frontend/src/pages/Room/containers/ChatContainer/index.tsx
  frontend/src/pages/Room/containers/GameContentContainer/index.tsx
  frontend/src/pages/Room/hooks/index.ts
  frontend/src/pages/Room/hooks/useMyCorrect.tsx
  frontend/yarn.lock
Labels: 배포 🚀🚀🚀

#100 feat: ChakraProvider breakpoints 적용
  frontend/.storybook/decorators/index.ts
  frontend/.storybook/decorators/withTheme.tsx
  frontend/.storybook/main.js
  frontend/.storybook/preview.js
  frontend/src/App.tsx
  frontend/src/pages/Room/containers/CanvasContainer/index.tsx
  frontend/src/pages/Room/containers/DevLogContainer/index.scss
  frontend/src/pages/Room/containers/ToolsContainer/index.tsx
  frontend/src/pages/Room/index.tsx
  frontend/src/styles/modules/mixin.scss
  frontend/src/theme.ts
Labels: 개선 😀, UI 😀

#99 feat: [게임] 반응형 레이아웃 설정
  frontend/.storybook/decorators/index.ts
  frontend/.storybook/decorators/withTheme.tsx
  frontend/.storybook/main.js
  frontend/.storybook/preview.js
  frontend/src/App.tsx
  frontend/src/pages/Room/components/PaletteColor/index.scss
  frontend/src/pages/Room/containers/DevLogContainer/index.scss
  frontend/src/pages/Room/containers/ToolsContainer/index.scss
  frontend/src/pages/Room/containers/ToolsContainer/index.tsx
  frontend/src/pages/Room/containers/UserListContainer/index.scss
  frontend/src/pages/Room/index.scss
  frontend/src/pages/Room/index.tsx
  frontend/src/styles/modules/mixin.scss
  frontend/src/theme.ts
Labels: 개선 😀, UI 😀

#103 feat: 다음턴 플레이어 프로필 이모지 노출 추가
  frontend/src/pages/Room/components/overlay/NextTurnContent/index.tsx
  frontend/src/pages/Room/containers/GameContentContainer/index.tsx
  frontend/src/pages/Room/hooks/usePainterInfo.tsx
Labels: 개선 😀, UI 😀

#102 feat: 랜덤하게 생성된 단어 참여자와 싱크 처리
  frontend/src/constants/index.ts
  frontend/src/helpers/utils.ts
  frontend/src/mocks/store/index.ts
  frontend/src/pages/Room/hooks/useGameHandler.tsx
  frontend/src/pages/Room/hooks/useGameSync.tsx
  frontend/src/store/models/game.ts
Labels: 기능 😀

#101 fix: 그리기 클리어시 큐배열 리셋
  frontend/src/core/drawing/drawing.ts
Labels: 버그 🐛

#104 deploy: Merge to master
  frontend/.storybook/decorators/index.ts
  frontend/.storybook/decorators/withTheme.tsx
  frontend/.storybook/main.js
  frontend/.storybook/preview.js
  frontend/src/App.tsx
  frontend/src/constants/index.ts
  frontend/src/core/drawing/drawing.ts
  frontend/src/helpers/utils.ts
  frontend/src/mocks/store/index.ts
  frontend/src/pages/Room/components/PaletteColor/index.scss
  frontend/src/pages/Room/components/overlay/NextTurnContent/index.tsx
  frontend/src/pages/Room/containers/DevLogContainer/index.scss
  frontend/src/pages/Room/containers/GameContentContainer/index.tsx
  frontend/src/pages/Room/containers/ToolsContainer/index.scss
  frontend/src/pages/Room/containers/ToolsContainer/index.tsx
  frontend/src/pages/Room/containers/UserListContainer/index.scss
  frontend/src/pages/Room/hooks/useGameHandler.tsx
  frontend/src/pages/Room/hooks/useGameSync.tsx
  frontend/src/pages/Room/hooks/usePainterInfo.tsx
  frontend/src/pages/Room/index.scss
  frontend/src/pages/Room/index.tsx
  frontend/src/store/models/game.ts
  frontend/src/styles/modules/mixin.scss
  frontend/src/theme.ts
Labels: 배포 🚀🚀🚀

#105 feat: 참여자 준비 현황 화면 추가
  frontend/src/mocks/store/index.ts
  frontend/src/pages/Room/components/GameRound/index.tsx
  frontend/src/pages/Room/components/GameTimer/index.tsx
  frontend/src/pages/Room/components/index.ts
  frontend/src/pages/Room/components/overlay/ReadyContent/index.scss
  frontend/src/pages/Room/components/overlay/ReadyContent/index.tsx
  frontend/src/pages/Room/components/overlay/ResultLayer/index.scss
  frontend/src/pages/Room/components/overlay/ResultLayer/index.tsx
  frontend/src/pages/Room/containers/CanvasContainer/index.tsx
  frontend/src/pages/Room/containers/DevLogContainer/index.tsx
  frontend/src/pages/Room/containers/GameContentContainer/index.tsx
  frontend/src/pages/Room/hooks/index.ts
  frontend/src/pages/Room/hooks/useFirstUser.tsx
  frontend/src/pages/Room/hooks/useGameHandler.tsx
  frontend/src/pages/Room/hooks/useGameStatus.tsx
  frontend/src/pages/Room/hooks/useGameSync.tsx
  frontend/src/pages/Room/index.tsx
  frontend/src/store/models/game.ts
  frontend/src/stories/2-Room.stories.tsx
  frontend/src/types/enums.ts
Labels: 기능 😀

#106 feat: 브러시 사이즈 프리뷰 추가
  frontend/src/pages/Room/components/PaletteSlider/index.tsx
  frontend/src/pages/Room/containers/ToolsContainer/index.scss
  frontend/src/pages/Room/containers/ToolsContainer/index.tsx
Labels: 개선 😀, UI 😀

#107 feat: 순위 발표 화면 로직 수정
  frontend/src/mocks/store/room.ts
  frontend/src/pages/Room/components/overlay/GameOverContent/index.tsx
Labels: 기능 😀

#108 deploy: Merge to master
  frontend/src/mocks/store/index.ts
  frontend/src/mocks/store/room.ts
  frontend/src/pages/Room/components/GameRound/index.tsx
  frontend/src/pages/Room/components/GameTimer/index.tsx
  frontend/src/pages/Room/components/PaletteSlider/index.tsx
  frontend/src/pages/Room/components/index.ts
  frontend/src/pages/Room/components/overlay/GameOverContent/index.tsx
  frontend/src/pages/Room/components/overlay/ReadyContent/index.scss
  frontend/src/pages/Room/components/overlay/ReadyContent/index.tsx
  frontend/src/pages/Room/components/overlay/ResultLayer/index.scss
  frontend/src/pages/Room/components/overlay/ResultLayer/index.tsx
  frontend/src/pages/Room/containers/CanvasContainer/index.tsx
  frontend/src/pages/Room/containers/DevLogContainer/index.tsx
  frontend/src/pages/Room/containers/GameContentContainer/index.tsx
  frontend/src/pages/Room/containers/ToolsContainer/index.scss
  frontend/src/pages/Room/containers/ToolsContainer/index.tsx
  frontend/src/pages/Room/hooks/index.ts
  frontend/src/pages/Room/hooks/useFirstUser.tsx
  frontend/src/pages/Room/hooks/useGameHandler.tsx
  frontend/src/pages/Room/hooks/useGameStatus.tsx
  frontend/src/pages/Room/hooks/useGameSync.tsx
  frontend/src/pages/Room/index.tsx
  frontend/src/store/models/game.ts
  frontend/src/stories/2-Room.stories.tsx
  frontend/src/types/enums.ts
Labels: 배포 🚀🚀🚀
